# Generated by Django 4.2.4 on 2023-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiworkshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='basicconfig',
            name='key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
