# Generated by Django 4.2.4 on 2023-08-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiworkshop', '0002_remove_basicconfig_id_alter_basicconfig_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('image_url', models.CharField(max_length=1000)),
                ('prompt', models.CharField(max_length=1000)),
            ],
        ),
    ]
