# Generated by Django 4.2.4 on 2023-08-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiworkshop', '0003_artwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='prompt',
            new_name='image_prompt',
        ),
    ]
