# Generated by Django 4.2.4 on 2023-08-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiworkshop', '0004_rename_prompt_artwork_image_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
