# Generated by Django 4.2.4 on 2023-08-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiworkshop', '0005_alter_artwork_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
