# Generated by Django 4.2.4 on 2023-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiworkshop', '0006_alter_artwork_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image_url',
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.FileField(default='test', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
