# Generated by Django 4.2.4 on 2023-10-03 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artwork',
            unique_together={('user', 'created_at')},
        ),
    ]
