# Generated by Django 4.2.4 on 2023-10-03 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_customuser_date_joined_and_more'),
        ('workshop', '0002_alter_artwork_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushoverSettings',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_key', models.CharField(max_length=30)),
            ],
        ),
    ]
