# Generated by Django 4.2.4 on 2023-10-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_pushoversettings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('task', 'run_at')},
            },
        ),
    ]
