# Generated by Django 4.2.4 on 2023-10-08 15:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_customuser_date_joined_and_more'),
        ('workshop', '0005_celerytaskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalDavSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('caldav_url', models.URLField(max_length=255)),
                ('calendar_url', models.URLField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='issue_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
