# Generated by Django 4.2.6 on 2023-10-17 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_staff'),
        ('workshop', '0006_caldavsettings_alter_usersettings_issue_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenWeatherSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
