# Generated by Django 4.2.6 on 2023-10-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_openweathersettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openweathersettings',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='openweathersettings',
            old_name='lon',
            new_name='longitude',
        ),
    ]
