# Generated by Django 4.2.6 on 2023-11-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_alter_artstyle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='title',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
