# Generated by Django 4.2.6 on 2023-11-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_artwork_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artstyle',
            old_name='user',
            new_name='user_set',
        ),
        migrations.AlterField(
            model_name='daytimesettings',
            name='timezone_hour_offset',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
