# Generated by Django 4.2.6 on 2023-11-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_rename_user_set_artstyle_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
